version: '3.3'
services:
  axonserver-1:
    image: axoniq/axonserver:latest-jdk-17
    pull_policy: always
    hostname: axonserver-1
    environment:
      - axoniq_console_authentication=c44f6e05-0-asc:56044bbdfc234a0aa140ff774869087e
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    networks:
      - axon-server

networks:
  axon-server: