###
POST http://localhost:8080/carts
Content-Type: application/json

{
  "id": "bbcc74c9-74d1-43d5-a6df-880bc520b9fb"
}

###
POST http://localhost:8080/carts/5e1c7418-ef31-40eb-bc31-9e87091da13a/add-item
Content-Type: application/json

{
  "cartid": "5e1c7418-ef31-40eb-bc31-9e87091da13a",
  "productid": "45c38dfa-5996-426a-a31f-2d058b3d2a4a",
  "quantity" : 2,
  "baseprice" : 10.99
}
###
POST http://localhost:8080/check/add-item-to-cart
Content-Type: application/json

{
  "cartid": "fc3319e6-daf7-4b49-8861-278ac0a0eba8",
  "productid": "45c38dfa-5996-426a-a31f-2d058b3d2a4a",
  "quantity" : 4,
  "basePrice" : 17.99
}

###
POST http://localhost:8080/check/carts
Content-Type: application/json

