### Create cart
POST http://localhost:8080/carts
Content-Type: application/json

{
  "cartid": "bbcc74c9-74d1-43d5-a6df-880bc520b9fb"
}

### Add item to cart
POST http://localhost:8080/carts/bbcc74c9-74d1-43d5-a6df-880bc520b9fb/add-item
Content-Type: application/json

{
  "cartid": "bbcc74c9-74d1-43d5-a6df-880bc520b9fb",
  "productid": "45c38dfa-5996-426a-a31f-2d058b3d2a4a",
  "quantity": 4,
  "baseprice": 17.99
}

